<a href="https://colab.research.google.com/github/JYRUS19/20220702-Python/blob/main/20220730.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 使用 Teachable Machine 幫我們訓練好的模型

In [29]:
# 解壓縮選取的檔案
!unzip modle.zip

Archive:  modle.zip
replace keras_model.h5? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

In [ ]:
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

# Load the model
model = load_model('keras_model.h5')

# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
# Replace this with the path to your image
image = Image.open('phone.jpg')
#resize the image to a 224x224 with the same strategy as in TM2:
#resizing the image to be at least 224x224 and then cropping from the center
size = (224, 224)
image = ImageOps.fit(image, size, Image.ANTIALIAS)

#turn the image into a numpy array
image_array = np.asarray(image)
# Normalize the image
normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
# Load the image into the array
data[0] = normalized_image_array

# run the inference
prediction = model.predict(data)
print(prediction)


[[0.6541428  0.33998552 0.00587173]]


## 使用Gradio打包上面的模型來使用

In [ ]:
!pip install gradio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [31]:
def classify(image):
  # Load the model
  model = load_model('keras_model.h5')
  #儲存被上傳的圖片
  #image.save(f"{random.randint(0, 10000):05}.jpg")

  # Create the array of the right shape to feed into the keras model
  # The 'length' or number of images you can put into the array is
  # determined by the first position in the shape tuple, in this case 1.
  data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
  #resize the image to a 224x224 with the same strategy as in TM2:
  #resizing the image to be at least 224x224 and then cropping from the center
  size = (224, 224)
  image = ImageOps.fit(image, size, Image.ANTIALIAS)

  #turn the image into a numpy array
  image_array = np.asarray(image)
  # Normalize the image
  normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
  # Load the image into the array
  data[0] = normalized_image_array

  # run the inference
  prediction = model.predict(data)
  labels = ["手機", "水壺", "手錶"]
  return labels[np.argmax(prediction)]

In [32]:
import gradio as gr

In [33]:
gr.Interface(classify, inputs=gr.Image(type="pil"), outputs="text").launch(share=True)

Colab notebook detected. To show errors in colab notebook, set `debug=True` in `launch()`
Running on public URL: https://27549.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces: https://huggingface.co/spaces


(<gradio.routes.App at 0x7f14fd2716d0>,
 'http://127.0.0.1:7865/',
 'https://27549.gradio.app')

## 練習

請輸出0-15的二進位及十六進位數值

In [40]:
for i in range(16):
  print(f"{i:2}的二進位是: {i:b}")

 0的二進位是: 0
 1的二進位是: 1
 2的二進位是: 10
 3的二進位是: 11
 4的二進位是: 100
 5的二進位是: 101
 6的二進位是: 110
 7的二進位是: 111
 8的二進位是: 1000
 9的二進位是: 1001
10的二進位是: 1010
11的二進位是: 1011
12的二進位是: 1100
13的二進位是: 1101
14的二進位是: 1110
15的二進位是: 1111


In [41]:
for i in range(16):
  print(f"{i:2}的二進位是: {i:04b}")

 0的二進位是: 0000
 1的二進位是: 0001
 2的二進位是: 0010
 3的二進位是: 0011
 4的二進位是: 0100
 5的二進位是: 0101
 6的二進位是: 0110
 7的二進位是: 0111
 8的二進位是: 1000
 9的二進位是: 1001
10的二進位是: 1010
11的二進位是: 1011
12的二進位是: 1100
13的二進位是: 1101
14的二進位是: 1110
15的二進位是: 1111


## Scikit-Learn 簡介

## 載入資料集

In [89]:
from sklearn import datasets

In [90]:
iris = datasets.load_iris()

In [91]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [92]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [93]:
X = iris.data

In [94]:
y = iris.target

In [95]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [96]:
y[0]

0

In [97]:
len(X)

150

## 拆分訓練集跟測試集

In [106]:
from sklearn.model_selection import train_test_split

In [107]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## 使用SVM來做分類

In [108]:
# 1.載入模型
from sklearn.svm import SVC

In [109]:
# 2.建立模型
clf = SVC()

In [110]:
# 3.訓練模型
clf.fit(X_train, y_train)

SVC()

In [118]:
# 計算模型準確度(Accuracy)
clf.score(X_test, y_test)

0.9666666666666667

In [112]:
# 4.使用模型
clf.predict(X_test)

array([1, 2, 2, 0, 2, 2, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0,
       2, 2, 2, 1, 1, 0, 1, 2])

## 使用 Random Forest 來做分類

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

In [114]:
# 1.載入模型
from sklearn.ensemble import RandomForestClassifier

In [115]:
# 2.建立模型
clf = RandomForestClassifier()

In [116]:
# 3.訓練模型
clf.fit(X_train, y_train)

RandomForestClassifier()

In [117]:
# 計算模型準確度(Accuracy)
clf.score(X_test, y_test)

0.9666666666666667

## 使用 Mediapipe 畫出手的關節點

In [119]:
!pip install mediapipe

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 32.9 MB 1.3 MB/s 


In [121]:
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

# For static images:
IMAGE_FILES = ['my_hand.jpg']
with mp_hands.Hands(
    static_image_mode=True,
    max_num_hands=2,
    min_detection_confidence=0.5) as hands:
  for idx, file in enumerate(IMAGE_FILES):
    # Read an image, flip it around y-axis for correct handedness output (see
    # above).
    image = cv2.flip(cv2.imread(file), 1)
    # Convert the BGR image to RGB before processing.
    results = hands.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

    # Print handedness and draw hand landmarks on the image.
    print('Handedness:', results.multi_handedness)
    if not results.multi_hand_landmarks:
      continue
    image_height, image_width, _ = image.shape
    annotated_image = image.copy()
    for hand_landmarks in results.multi_hand_landmarks:
      print('hand_landmarks:', hand_landmarks)
      print(
          f'Index finger tip coordinates: (',
          f'{hand_landmarks.landmark[mp_hands.HandLandmark.INDEX_FINGER_TIP].x * image_width}, '
          f'{hand_landmarks.landmark[mp_hands.HandLandmark.INDEX_FINGER_TIP].y * image_height})'
      )
      mp_drawing.draw_landmarks(
          annotated_image,
          hand_landmarks,
          mp_hands.HAND_CONNECTIONS,
          mp_drawing_styles.get_default_hand_landmarks_style(),
          mp_drawing_styles.get_default_hand_connections_style())
    cv2.imwrite(
        'my_hand' + str(idx) + '.png', cv2.flip(annotated_image, 1))
    # Draw hand world landmarks.
    if not results.multi_hand_world_landmarks:
      continue
    for hand_world_landmarks in results.multi_hand_world_landmarks:
      mp_drawing.plot_landmarks(
          hand_world_landmarks, mp_hands.HAND_CONNECTIONS, azimuth=5)


In [ ]:
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

file = 'my_hand.jpg'
with mp_hands.Hands(static_image_mode=True,max_num_hands=2,min_detection_confidence=0.5) as hands:
  image = cv2.flip(cv2.imread(file), 1)
  results = hands.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

  image_height, image_width, _ = image.shape
  annotated_image = image.copy()
  for hand_landmarks in results.multi_hand_landmarks:
    mp_drawing.draw_landmarks(
        annotated_image,
        hand_landmarks,
        mp_hands.HAND_CONNECTIONS,
        mp_drawing_styles.get_default_hand_landmarks_style(),
        mp_drawing_styles.get_default_hand_connections_style())
  cv2.imwrite('my_hand.png', cv2.flip(annotated_image, 1))

im = Image.open('my_hand.png')
im

## HOME WORK

寫一個Gradio 的APP,輸入手的圖形後,輸出畫上關節點的圖形

In [ ]:
import matplotlib.pyplot as plt
def show(image):
  plt.imsave("test.jpg",image)
  return "Good"

gr.Interface(show, inputs="image", outputs="text").launch(share=True)

In [ ]:
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

def draw_landmarks(image):
  with mp_hands.Hands(static_image_mode=True,max_num_hands=2,min_detection_confidence=0.5) as hands:
    image = cv2.flip(image, 1)
    results = hands.process(image)

    image_height, image_width, _ = image.shape
    annotated_image = image.copy()
    for hand_landmarks in results.multi_hand_landmarks:
      mp_drawing.draw_landmarks(
          annotated_image,
          hand_landmarks,
          mp_hands.HAND_CONNECTIONS,
          mp_drawing_styles.get_default_hand_landmarks_style(),
          mp_drawing_styles.get_default_hand_connections_style())
    image = cv2.flip(annotated_image, 1)
    return image

In [ ]:
gr.Interface(draw_landmarks, inputs="image", outputs="image").launch(share=True)